### ISSUE TITLE
Audit migraine patients

### ISSUE THREAD

**Issue by AdamSwenson** [PainNarrativesLab/CommonResources#21]
Audit the migraine patient spreadsheet. (Stored in the UserData folder of Google Drive, contact @AdamSwenson if you need access).

**Comment by Cesar-Bernal** [comment]
1) where should we categorize people who are working for a certain migraine research institute?
2) There were a couple of foreign language tweets which included the word 'migraine'. Where should these be categorized?
3) Should studies done on migraines be classified on 'other', or 'organization'?
